# Streamlit Cloud에서 사용할 환경 변수 설정
# ⚠️  중요: 이 파일의 값들은 기본값입니다. 
# 실제 운영에서는 Streamlit Cloud 웹 인터페이스의 "Secrets" 섹션에서 설정하세요!

# OpenAI API 설정 (Streamlit Cloud Secrets에서 실제 키로 교체 필요)
OPENAI_API_KEY = "your-openai-api-key-here"
OPENAI_MODEL = "gpt-5-mini"
OPENAI_PROMPT_ID = "pmpt_68f36e44eab08196b4e75067a3074b7b0c099d8443a9dd49"
OPENAI_PROMPT_VERSION = "4"

[supabase]
url = "https://zttosbzbwkgqkpsdgpcx.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dG9zYnpid2tncWtwc2RncGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTMzNDQsImV4cCI6MjA3NDM4OTM0NH0.bxc9FOllQc57vlC52aO4lRE0RqxX5Uwv9TchkuYNQ08"

[app]
title = "Connecta Manager"
description = "인플루언서 캠페인 관리 시스템"

# 개발 모드 설정 (false로 설정하면 일반 모드)
dev_mode = false