# Streamlit Cloud에서 사용할 환경 변수 설정
# 실제 값은 Streamlit Cloud의 Secrets에서 설정하세요

[supabase]
url = "https://zttosbzbwkgqkpsdgpcx.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dG9zYnpid2tncWtwc2RncGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTMzNDQsImV4cCI6MjA3NDM4OTM0NH0.bxc9FOllQc57vlC52aO4lRE0RqxX5Uwv9TchkuYNQ08"


[app]
title = "Connecta Manager"
description = "인플루언서 캠페인 관리 시스템"

# 개발 모드 설정 (false로 설정하면 일반 모드)
dev_mode = false